# Generated by Django 3.0.6 on 2020-05-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywebsites',
            name='address_local',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mywebsites',
            name='address_permanent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mywebsites',
            name='birthday',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mywebsites',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mywebsites',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mywebsites',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mywebsites',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mywebsites',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mywebsites',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
